# src/report_generator.py
# ══════════════════════════════════════════════════════════════════════════
# PDF REPORT GENERATOR
# Creates a downloadable PDF report of the full resume analysis.
# Uses fpdf2 library (pip install fpdf2).
# ══════════════════════════════════════════════════════════════════════════

import os
import io
import logging
from datetime import datetime
from typing import Dict, List

logger = logging.getLogger(__name__)

try:
    from fpdf import FPDF
    FPDF_AVAILABLE = True
except ImportError:
    FPDF_AVAILABLE = False
    logger.warning("fpdf2 not installed. Run: pip install fpdf2")


class ResumeReportPDF(FPDF):
    """
    Custom PDF class with header and footer built-in.
    Inherits from FPDF and overrides header() and footer().
    These are called automatically on every page.
    """

    def header(self):
        """Page header — printed at top of every page."""
        self.set_fill_color(102, 126, 234)   # Purple color (RGB)
        self.rect(0, 0, 210, 18, 'F')        # Filled rectangle (full width, 18mm)
        self.set_text_color(255, 255, 255)    # White text
        self.set_font('Helvetica', 'B', 12)
        self.set_xy(10, 4)
        self.cell(0, 10, 'AI Career Analyzer — Resume Analysis Report', ln=False)
        self.set_text_color(0, 0, 0)          # Reset to black
        self.ln(18)                           # Move below header

    def footer(self):
        """Page footer — printed at bottom of every page."""
        self.set_y(-15)                       # 15mm from bottom
        self.set_font('Helvetica', 'I', 8)
        self.set_text_color(128, 128, 128)
        self.cell(0, 10,
                  f'Page {self.page_no()} | Generated by AI Career Analyzer | '
                  f'{datetime.now().strftime("%d %b %Y")}',
                  align='C')


def generate_report(
    resume_data:   dict,
    ats_result:    dict,
    match_result:  dict,
    career_result: dict,
    skills_result: dict,
) -> bytes:
    """
    Generate a complete PDF analysis report.

    Args:
        resume_data:   Parsed resume dict
        ats_result:    ATS score result dict
        match_result:  Job matching result dict
        career_result: Career recommendation result dict
        skills_result: Skill extraction result dict

    Returns:
        PDF file as bytes (ready for st.download_button in Streamlit)
    """
    if not FPDF_AVAILABLE:
        return b""

    pdf = ResumeReportPDF()
    pdf.set_auto_page_break(auto=True, margin=20)  # Auto page break with 20mm margin
    pdf.add_page()

    # ── Helper functions ────────────────────────────────────────────────
    def section_title(text: str):
        """Print a colored section title."""
        pdf.ln(4)
        pdf.set_fill_color(240, 240, 255)
        pdf.set_font('Helvetica', 'B', 12)
        pdf.set_text_color(80, 40, 160)
        pdf.cell(0, 8, text, ln=True, fill=True)
        pdf.set_text_color(0, 0, 0)
        pdf.ln(2)

    def body_text(text: str, indent: int = 0):
        """Print a body text line."""
        pdf.set_font('Helvetica', '', 10)
        pdf.set_x(10 + indent)
        pdf.multi_cell(0, 6, text)

    def score_bar(label: str, score: float, max_score: float = 100):
        """Print a label + visual bar for a score."""
        pdf.set_font('Helvetica', '', 9)
        pdf.set_x(10)
        pdf.cell(60, 6, f"{label}:", ln=False)

        # Color based on score
        pct = score / max_score
        if pct >= 0.8:
            r, g, b = 46, 204, 113    # Green
        elif pct >= 0.6:
            r, g, b = 52, 152, 219   # Blue
        elif pct >= 0.4:
            r, g, b = 243, 156, 18   # Orange
        else:
            r, g, b = 231, 76, 60    # Red

        # Draw score bar
        bar_width = 80
        fill_width = bar_width * pct
        pdf.set_fill_color(230, 230, 230)
        pdf.rect(pdf.get_x(), pdf.get_y() + 1, bar_width, 4, 'F')
        pdf.set_fill_color(r, g, b)
        pdf.rect(pdf.get_x(), pdf.get_y() + 1, fill_width, 4, 'F')
        pdf.set_x(pdf.get_x() + bar_width + 5)
        pdf.cell(20, 6, f"{score:.0f}%", ln=True)

    # ════════════════════════════════════════════════════════════════════
    # PAGE 1 — SUMMARY
    # ════════════════════════════════════════════════════════════════════

    # Candidate name + date
    pdf.set_font('Helvetica', 'B', 18)
    pdf.set_text_color(40, 40, 80)
    name = resume_data.get('name', 'Candidate')
    pdf.cell(0, 10, f"Analysis Report: {name}", ln=True, align='C')

    pdf.set_font('Helvetica', '', 10)
    pdf.set_text_color(100, 100, 100)
    pdf.cell(0, 6, f"Generated: {datetime.now().strftime('%d %B %Y %H:%M')}", ln=True, align='C')
    pdf.ln(6)

    # Overall ATS Score (big number)
    ats_score = ats_result.get('overall_score', 0)
    grade     = ats_result.get('grade', 'N/A')
    label     = ats_result.get('label', '')

    pdf.set_font('Helvetica', 'B', 36)
    if ats_score >= 75:
        pdf.set_text_color(46, 204, 113)
    elif ats_score >= 55:
        pdf.set_text_color(52, 152, 219)
    else:
        pdf.set_text_color(231, 76, 60)
    pdf.cell(0, 16, f"{ats_score:.0f}%", ln=True, align='C')

    pdf.set_font('Helvetica', 'B', 14)
    pdf.set_text_color(60, 60, 60)
    pdf.cell(0, 8, f"Grade: {grade}  |  {label}", ln=True, align='C')
    pdf.set_text_color(0, 0, 0)
    pdf.ln(4)

    # ── ATS Component Scores ─────────────────────────────────────────
    section_title("ATS Score Breakdown")
    component_scores = ats_result.get('component_scores', {})
    for component, score in component_scores.items():
        display_name = component.replace('_', ' ').title()
        score_bar(display_name, score)

    # ── Career Recommendation ────────────────────────────────────────
    section_title("Career Recommendation")
    top_career = career_result.get('career', 'Unknown')
    confidence = career_result.get('confidence', 0)
    pdf.set_font('Helvetica', 'B', 12)
    pdf.cell(0, 8, f"Best Match: {top_career} ({confidence:.0f}% confidence)", ln=True)
    pdf.ln(2)

    # ── Skills Found ────────────────────────────────────────────────
    section_title("Skills Detected")
    all_skills = skills_result.get('all_skills', [])
    pdf.set_font('Helvetica', '', 10)
    skills_text = ', '.join(all_skills[:30])  # First 30 skills
    pdf.multi_cell(0, 6, skills_text)

    # ── Strengths ────────────────────────────────────────────────────
    section_title("Strengths")
    for strength in ats_result.get('strengths', []):
        body_text(f"  ✓  {strength}", indent=4)

    # ── Areas for Improvement ────────────────────────────────────────
    section_title("Areas for Improvement")
    for improvement in ats_result.get('improvements', []):
        body_text(f"  →  {improvement}", indent=4)

    # ── Missing Skills ───────────────────────────────────────────────
    missing = ats_result.get('missing_skills', [])
    if missing:
        section_title("Missing Skills to Add")
        body_text(', '.join(missing[:15]))

    # ── Resume Tips ──────────────────────────────────────────────────
    section_title("Professional Resume Tips")
    for tip in ats_result.get('resume_tips', []):
        body_text(f"  •  {tip}", indent=4)

    # ── Footer note ──────────────────────────────────────────────────
    pdf.ln(8)
    pdf.set_font('Helvetica', 'I', 9)
    pdf.set_text_color(120, 120, 120)
    pdf.multi_cell(0, 5,
        "This report was generated by the AI Career Analyzer using NLP and ML models. "
        "Scores are estimates based on automated analysis and should be used as guidance, "
        "not definitive evaluations.")

    # Return PDF as bytes
    return bytes(pdf.output())