[theme]
base                   = "dark"
primaryColor           = "#6C63FF"
backgroundColor        = "#0F0F1A"
secondaryBackgroundColor = "#16162A"
textColor              = "#F1F0FF"
font                   = "sans serif"

[server]
maxUploadSize          = 5
enableCORS             = false
enableXsrfProtection   = true

[browser]
gatherUsageStats       = false